name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['*.md', LICENSE, .gitignore, .husky/**]
  pull_request:
    branches: [main]
    paths-ignore: ['*.md', LICENSE, .gitignore, .husky/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0
  NODE_VERSION: 20

jobs:
  cache-deps:
    name: Install & cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

  lint:
    name: Lint & format
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        id: install
        run: yarn install --frozen-lockfile

      - name: Lint typescript
        run: yarn run lint:code

      - name: Lint styles
        if: always() && steps.install.outcome == 'success'
        run: yarn run lint:styles

      - name: Format
        if: always() && steps.install.outcome == 'success'
        run: yarn run format

  typecheck:
    name: Typecheck
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn run typecheck

  test:
    name: Test
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn run test:ci

  build:
    name: Build
    needs: [lint, typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          retention-days: 7

  deploy:
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get build
        uses: actions/download-artifact@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
